spring:

  #DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: ${jdbc.database.url}
    username: ${jdbc.database.username}
    password: ${jdbc.database.password}

  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    format_sql: false

  #FLYWAY
  flyway:
    check-location: true
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix:
    baseline-version: 0

server:
  error:
    include-stacktrace: never