endpoints:
  individual:
    name: individualClient
    protocol: https
    host: host de produção
    port: porta de produção
    url: ${endpoints.individual.protocol}://${endpoints.individual.host}:${endpoints.individual.port}